import SwiftUI
#if canImport(UIKit)
import PhotosUI
import UIKit
#endif

/// A reusable sheet for importing data pasted as JSON — typically generated by an external AI
/// assistant asked to fill in nutrition values that aren't easy to know exactly (no label, home
/// cooking, restaurant food, ...). Shows a copyable prompt — instructions any AI can follow plus a
/// generic template of the expected JSON — then lets the user paste back whatever it returns,
/// validating it with `onImport` before dismissing.
///
/// `additionalFields` lets a caller inject extra form controls (e.g. a required name field or a
/// picker) above the JSON sections, for data that's better entered directly in the app than
/// round-tripped through the AI's JSON — `isReadyToImport` then gates the Importar button on
/// whatever those controls need to be valid.
struct JSONImportSheet<AdditionalFields: View>: View {
    @Environment(\.dismiss) private var dismiss

    let title: String
    let prompt: AIImportPrompt
    /// For the user: what the import is useful for and how it behaves.
    let instructions: String
    var additionalFields: () -> AdditionalFields
    var isReadyToImport: () -> Bool
    /// Parses/applies the pasted JSON. Throws to show a validation error instead of dismissing.
    let onImport: (String) throws -> Void

    @State private var pastedText = ""
    @State private var errorMessage: String?
    @State private var descriptionText = ""
    @State private var copied: CopyTarget?
    @FocusState private var isPasteFieldFocused: Bool
    @FocusState private var isDescriptionFocused: Bool

    #if canImport(UIKit)
    @State private var photo: UIImage?
    @State private var photoItem: PhotosPickerItem?
    @State private var showingCamera = false
    @State private var showingShare = false
    #endif

    private enum CopyTarget { case text, photo }

    private var isPastedTextEmpty: Bool {
        pastedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    /// The instructions with the user's own description appended where the prompt ends
    /// ("O que quero registar:").
    private var fullText: String {
        let description = descriptionText.trimmingCharacters(in: .whitespacesAndNewlines)
        #if canImport(UIKit)
        let hasPhoto = photo != nil
        #else
        let hasPhoto = false
        #endif
        let ending = description.isEmpty ? (hasPhoto ? "ver a foto em anexo." : "") : description
        return ending.isEmpty ? prompt.text : prompt.text + " " + ending
    }

    var body: some View {
        NavigationStack {
            Form {
                additionalFields()

                Section {
                    #if canImport(UIKit)
                    photoControls
                    #endif

                    TextField(prompt.descriptionPlaceholder, text: $descriptionText, axis: .vertical)
                        .lineLimit(2...5)
                        .focused($isDescriptionFocused)

                    #if canImport(UIKit)
                    Button {
                        shareWithAI()
                    } label: {
                        Label(photo == nil ? "Enviar para a IA" : "Enviar Foto para a IA", systemImage: "square.and.arrow.up")
                    }

                    Button {
                        openGemini()
                    } label: {
                        Label("Copiar Texto e Abrir Gemini", systemImage: "sparkles")
                    }
                    #endif

                    Button {
                        copyText()
                    } label: {
                        Label(copied == .text ? "Copiado" : "Copiar Texto", systemImage: copied == .text ? "checkmark" : "doc.on.doc")
                    }

                    #if canImport(UIKit)
                    if photo != nil {
                        Button {
                            copyPhoto()
                        } label: {
                            Label(copied == .photo ? "Copiada" : "Copiar Foto", systemImage: copied == .photo ? "checkmark" : "photo.on.rectangle")
                        }
                    }
                    #endif

                    DisclosureGroup("Ver instruções para a IA") {
                        ScrollView {
                            Text(fullText)
                                .font(.system(.caption2, design: .monospaced))
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .textSelection(.enabled)
                        }
                        .frame(maxHeight: 220)
                    }
                } header: {
                    Text("Pedir à IA")
                } footer: {
                    Text("\(instructions) Tira uma foto (opcional) e descreve o que queres registar. \"Enviar Foto para a IA\" partilha a foto (escolhe o Gemini; se não aparecer, procura-o em \"Mais\") e deixa o texto copiado — cola-o na conversa. \"Copiar Texto e Abrir Gemini\" abre o Gemini com o texto copiado; anexa lá a foto. Depois cola aqui a resposta.")
                }

                Section {
                    TextEditor(text: $pastedText)
                        .font(.system(.footnote, design: .monospaced))
                        .autocorrectionDisabled()
                        #if os(iOS)
                        .textInputAutocapitalization(.never)
                        #endif
                        .frame(minHeight: 160)
                        .focused($isPasteFieldFocused)

                    HStack {
                        PasteButton(payloadType: String.self) { strings in
                            guard let text = strings.first else { return }
                            Task { @MainActor in
                                pastedText = text
                                isPasteFieldFocused = false
                            }
                        }
                        .labelStyle(.titleAndIcon)

                        Spacer()

                        if !isPastedTextEmpty {
                            Button("Limpar", role: .destructive) { pastedText = "" }
                                .buttonStyle(.borderless)
                        }
                    }
                } header: {
                    Text("Resposta da IA")
                } footer: {
                    Text("Podes colar a resposta tal como vem: texto à volta do JSON ou blocos de código são ignorados.")
                }
            }
            .scrollDismissesKeyboard(.interactively)
            .navigationTitle(title)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancelar") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Importar") { attemptImport() }
                        .disabled(isPastedTextEmpty || !isReadyToImport())
                }
                ToolbarItemGroup(placement: .keyboard) {
                    Spacer()
                    Button("Concluído") {
                        isPasteFieldFocused = false
                        isDescriptionFocused = false
                    }
                }
            }
            #if canImport(UIKit)
            .onChange(of: photoItem) {
                guard let photoItem else { return }
                Task {
                    if let data = try? await photoItem.loadTransferable(type: Data.self), let image = UIImage(data: data) {
                        photo = image.downscaled()
                    }
                    self.photoItem = nil
                }
            }
            .fullScreenCover(isPresented: $showingCamera) {
                CameraPicker { image in photo = image.downscaled() }
                    .ignoresSafeArea()
            }
            .sheet(isPresented: $showingShare) {
                // One kind of item only: the share sheet hides any app whose extension doesn't
                // accept *every* item, and AI apps (Gemini included) tend not to take an image and
                // a long text together. The text is on the clipboard already (see `shareWithAI`).
                ActivityShareSheet(items: [photo ?? fullText as Any])
                    .presentationDetents([.medium, .large])
                    .ignoresSafeArea()
            }
            #endif
            .alert(
                "Erro ao Importar",
                isPresented: Binding(
                    get: { errorMessage != nil },
                    set: { if !$0 { errorMessage = nil } }
                )
            ) {
                Button("OK", role: .cancel) { errorMessage = nil }
            } message: {
                Text(errorMessage ?? "")
            }
        }
    }

    #if canImport(UIKit)
    /// Take a photo (when there's a camera) or pick one from the library, with a preview once set.
    @ViewBuilder
    private var photoControls: some View {
        if let photo {
            HStack {
                Image(uiImage: photo)
                    .resizable()
                    .scaledToFill()
                    .frame(width: 72, height: 72)
                    .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
                Text("Foto pronta a enviar")
                    .foregroundStyle(.secondary)
                Spacer()
                Button("Remover", role: .destructive) { self.photo = nil }
                    .buttonStyle(.borderless)
            }
        }
        HStack(spacing: 12) {
            if CameraPicker.isAvailable {
                Button {
                    showingCamera = true
                } label: {
                    Label("Tirar Foto", systemImage: "camera")
                        .labelStyle(.titleAndIcon)
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(.bordered)
            }
            PhotosPicker(selection: $photoItem, matching: .images) {
                Label("Galeria", systemImage: "photo")
                    .labelStyle(.titleAndIcon)
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.bordered)
        }
    }

    /// Opens the share sheet with the photo (or the text, when there's no photo), and puts the
    /// text on the clipboard so it can be pasted into the AI's chat next to the shared photo.
    private func shareWithAI() {
        UIPasteboard.general.string = fullText
        isDescriptionFocused = false
        showingShare = true
    }

    /// Copies the text (and opens Gemini) for when Gemini doesn't show up in the share sheet: the
    /// photo can then be attached from Gemini's own camera/gallery button. The gemini.google.com
    /// link opens the Gemini app when it's installed (universal link), otherwise Safari.
    private func openGemini() {
        UIPasteboard.general.string = fullText
        isDescriptionFocused = false
        if let url = URL(string: "https://gemini.google.com/app") {
            UIApplication.shared.open(url)
        }
    }

    private func copyPhoto() {
        guard let photo else { return }
        UIPasteboard.general.image = photo
        flashCopied(.photo)
    }
    #endif

    private func copyText() {
        #if canImport(UIKit)
        UIPasteboard.general.string = fullText
        #endif
        flashCopied(.text)
    }

    private func flashCopied(_ target: CopyTarget) {
        withAnimation { copied = target }
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
            withAnimation { if copied == target { copied = nil } }
        }
    }

    private func attemptImport() {
        do {
            try onImport(pastedText)
            dismiss()
        } catch {
            errorMessage = error.localizedDescription
        }
    }
}

extension JSONImportSheet where AdditionalFields == EmptyView {
    /// Convenience for the common case with no extra fields above the JSON sections.
    init(
        title: String,
        prompt: AIImportPrompt,
        instructions: String,
        onImport: @escaping (String) throws -> Void
    ) {
        self.init(
            title: title,
            prompt: prompt,
            instructions: instructions,
            additionalFields: { EmptyView() },
            isReadyToImport: { true },
            onImport: onImport
        )
    }
}

#Preview {
    JSONImportSheet(
        title: "Importar Alimento",
        prompt: AIJSONImport.foodPrompt,
        instructions: "Útil quando não há rótulo à mão."
    ) { _ in }
}
