import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

/// A reusable sheet for importing data pasted as JSON — typically generated by an external AI
/// assistant asked to fill in nutrition values that aren't easy to know exactly (no label, home
/// cooking, restaurant food, ...). Shows the expected JSON shape as a copyable example (to hand
/// to the AI as a prompt), then lets the user paste back whatever it returns, validating it with
/// `onImport` before dismissing.
///
/// `additionalFields` lets a caller inject extra form controls (e.g. a required name field or a
/// picker) above the JSON sections, for data that's better entered directly in the app than
/// round-tripped through the AI's JSON — `isReadyToImport` then gates the Importar button on
/// whatever those controls need to be valid.
struct JSONImportSheet<AdditionalFields: View>: View {
    @Environment(\.dismiss) private var dismiss

    let title: String
    let exampleJSON: String
    let instructions: String
    var additionalFields: () -> AdditionalFields
    var isReadyToImport: () -> Bool
    /// Parses/applies the pasted JSON. Throws to show a validation error instead of dismissing.
    let onImport: (String) throws -> Void

    @State private var pastedText = ""
    @State private var errorMessage: String?
    @State private var didCopy = false
    @FocusState private var isPasteFieldFocused: Bool

    private var isPastedTextEmpty: Bool {
        pastedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var body: some View {
        NavigationStack {
            Form {
                additionalFields()

                Section {
                    ScrollView {
                        Text(exampleJSON)
                            .font(.system(.caption2, design: .monospaced))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxHeight: 200)

                    Button {
                        copyExample()
                    } label: {
                        Label(didCopy ? "Copiado" : "Copiar Esquema", systemImage: didCopy ? "checkmark" : "doc.on.doc")
                    }
                } header: {
                    Text("Esquema JSON")
                } footer: {
                    Text(instructions)
                }

                Section("Colar Resultado da IA") {
                    TextEditor(text: $pastedText)
                        .font(.system(.footnote, design: .monospaced))
                        .autocorrectionDisabled()
                        #if os(iOS)
                        .textInputAutocapitalization(.never)
                        #endif
                        .frame(minHeight: 160)
                        .focused($isPasteFieldFocused)
                }
            }
            .scrollDismissesKeyboard(.interactively)
            .navigationTitle(title)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancelar") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Importar") { attemptImport() }
                        .disabled(isPastedTextEmpty || !isReadyToImport())
                }
                ToolbarItemGroup(placement: .keyboard) {
                    Spacer()
                    Button("Concluído") { isPasteFieldFocused = false }
                }
            }
            .alert(
                "Erro ao Importar",
                isPresented: Binding(
                    get: { errorMessage != nil },
                    set: { if !$0 { errorMessage = nil } }
                )
            ) {
                Button("OK", role: .cancel) { errorMessage = nil }
            } message: {
                Text(errorMessage ?? "")
            }
        }
    }

    private func copyExample() {
        #if canImport(UIKit)
        UIPasteboard.general.string = exampleJSON
        #endif
        withAnimation { didCopy = true }
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
            withAnimation { didCopy = false }
        }
    }

    private func attemptImport() {
        do {
            try onImport(pastedText)
            dismiss()
        } catch {
            errorMessage = error.localizedDescription
        }
    }
}

extension JSONImportSheet where AdditionalFields == EmptyView {
    /// Convenience for the common case with no extra fields above the JSON sections.
    init(
        title: String,
        exampleJSON: String,
        instructions: String,
        onImport: @escaping (String) throws -> Void
    ) {
        self.init(
            title: title,
            exampleJSON: exampleJSON,
            instructions: instructions,
            additionalFields: { EmptyView() },
            isReadyToImport: { true },
            onImport: onImport
        )
    }
}

#Preview {
    JSONImportSheet(
        title: "Importar Alimento",
        exampleJSON: AIJSONImport.foodExample,
        instructions: "Pede a uma IA os valores nutricionais deste alimento neste formato."
    ) { _ in }
}
